name: CI

on:
    push:

jobs:
    coding-standard:
        name: Coding standard
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
                    tools: prestissimo
            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: composer-${{ hashFiles('composer.lock') }}
            -   name: Install composer dependencies
                run: composer install --no-progress --no-suggest --ignore-platform-reqs
            -   name: Lint code
                run: composer lint

    static-analysis:
        name: Static analysis
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none
                    tools: prestissimo
            -   name: Cache composer dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: composer-${{ hashFiles('composer.lock') }}
            -   name: Install composer dependencies
                run: composer install --no-progress --no-suggest --ignore-platform-reqs
            -   name: Analyse code
                run: composer analyse
